"""empty message

Revision ID: 15d97e9274cf
Revises: c0b30e1b9147
Create Date: 2025-05-19 12:09:05.641522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15d97e9274cf'
down_revision: Union[str, None] = 'c0b30e1b9147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'prediction_score')
    op.drop_column('client', 'activity_count')
    op.drop_column('client', 'lifetime_value')
    op.drop_column('client', 'last_activity_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('last_activity_at', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('lifetime_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('activity_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('prediction_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
