"""added users

Revision ID: 543ff575de43
Revises: 3e3b22fd533c
Create Date: 2025-05-09 16:44:48.081209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '543ff575de43'
down_revision: Union[str, None] = '3e3b22fd533c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('manager', 'admin', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=True)
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=True)
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('website', 'instagram', 'whatsapp', 'telegram', 'facebook', 'referral', 'offline', 'other', name='clientsource'), nullable=False),
    sa.Column('segment', sa.Enum('retail', 'wholesale', 'vip', 'lead', 'prospect', 'churned', 'partner', 'test', name='clientsegment'), nullable=False),
    sa.Column('lifetime_value', sa.Float(), nullable=True),
    sa.Column('last_activity_at', sa.Date(), nullable=True),
    sa.Column('activity_count', sa.Integer(), nullable=True),
    sa.Column('prediction_score', sa.Float(), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_full_name'), 'clients', ['full_name'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=True)
    op.create_index(op.f('ix_clients_phone_number'), 'clients', ['phone_number'], unique=True)
    op.create_index(op.f('ix_clients_segment'), 'clients', ['segment'], unique=False)
    op.create_index(op.f('ix_clients_source'), 'clients', ['source'], unique=False)
    op.drop_index('ix_client_email', table_name='client')
    op.drop_index('ix_client_full_name', table_name='client')
    op.drop_index('ix_client_id', table_name='client')
    op.drop_index('ix_client_phone_number', table_name='client')
    op.drop_index('ix_client_segment', table_name='client')
    op.drop_index('ix_client_source', table_name='client')
    op.drop_table('client')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('segment', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('lifetime_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_activity_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('activity_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prediction_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('assigned_to', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='client_pkey')
    )
    op.create_index('ix_client_source', 'client', ['source'], unique=False)
    op.create_index('ix_client_segment', 'client', ['segment'], unique=False)
    op.create_index('ix_client_phone_number', 'client', ['phone_number'], unique=True)
    op.create_index('ix_client_id', 'client', ['id'], unique=True)
    op.create_index('ix_client_full_name', 'client', ['full_name'], unique=False)
    op.create_index('ix_client_email', 'client', ['email'], unique=True)
    op.drop_index(op.f('ix_clients_source'), table_name='clients')
    op.drop_index(op.f('ix_clients_segment'), table_name='clients')
    op.drop_index(op.f('ix_clients_phone_number'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_full_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
