"""empty message

Revision ID: e3b6a4c9e854
Revises: 
Create Date: 2025-05-19 12:17:05.215420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e3b6a4c9e854'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('manager', 'admin', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.Enum('website', 'instagram', 'whatsapp', 'telegram', 'facebook', 'referral', 'offline', 'other', name='clientsource'), nullable=False),
    sa.Column('segment', sa.Enum('retail', 'wholesale', 'vip', 'lead', 'prospect', 'churned', 'partner', 'test', name='clientsegment'), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=True)
    op.create_index(op.f('ix_client_full_name'), 'client', ['full_name'], unique=False)
    op.create_index(op.f('ix_client_id'), 'client', ['id'], unique=True)
    op.create_index(op.f('ix_client_phone_number'), 'client', ['phone_number'], unique=True)
    op.create_index(op.f('ix_client_segment'), 'client', ['segment'], unique=False)
    op.create_index(op.f('ix_client_source'), 'client', ['source'], unique=False)
    op.create_table('interaction',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('interaction_type', sa.Enum('call', 'meeting', 'email', 'chat', 'service', 'subscription', name='interactiontype'), nullable=False),
    sa.Column('interaction_datetime', sa.DateTime(), nullable=False),
    sa.Column('channel', sa.Enum('phone', 'telegram', 'whatsapp', 'instagram', name='channeltype'), nullable=False),
    sa.Column('interaction_status', sa.Enum('pending', 'completed', 'failed', 'cancelled', name='interactionstatus'), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('cost_center', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('churn_probability', sa.Float(), nullable=True),
    sa.Column('predicted_ltv', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interaction_client_id'), 'interaction', ['client_id'], unique=False)
    op.create_index(op.f('ix_interaction_id'), 'interaction', ['id'], unique=True)
    op.create_index(op.f('ix_interaction_interaction_datetime'), 'interaction', ['interaction_datetime'], unique=False)
    op.create_index(op.f('ix_interaction_interaction_status'), 'interaction', ['interaction_status'], unique=False)
    op.create_index(op.f('ix_interaction_user_id'), 'interaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_user_id'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_interaction_status'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_interaction_datetime'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_id'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_client_id'), table_name='interaction')
    op.drop_table('interaction')
    op.drop_index(op.f('ix_client_source'), table_name='client')
    op.drop_index(op.f('ix_client_segment'), table_name='client')
    op.drop_index(op.f('ix_client_phone_number'), table_name='client')
    op.drop_index(op.f('ix_client_id'), table_name='client')
    op.drop_index(op.f('ix_client_full_name'), table_name='client')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
