name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t app:ci .

    - name: Run container
      run: docker run -d --name app_ci app:ci

    - name: Apply migrations inside container
      run: docker exec app_ci bash -lc "alembic upgrade head"

    - name: Run tests inside container
      run: docker exec app_ci bash -lc "pytest"

    - name: Teardown
      if: always()
      run: |
        docker stop app_ci
        docker rm app_ci
