name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install deps
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Migrate db
      run: alembic upgrade head
    
    - name: Deploy
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
